// Generated by https://quicktype.io

export interface EventElement {
  id: number;
  title: string;
  rating: number;
  presenter: string;
  duration: number;
  description: string;
  imagePath: string;
  startDate: string;
  location: Location;
}

export interface Location {
  country: string;
  city: string;
  zipCode: string;
  address: string;
}
